ARG NODE_VERSION="24"
ARG DEBIAN_VARIANT="bookworm"

# Set base image
FROM mcr.microsoft.com/devcontainers/typescript-node:${NODE_VERSION}-${DEBIAN_VARIANT}

# Set current user to root
#USER root

# Update APT repository
ENV DEBIAN_FRONTEND=noninteractive
